name: Continuous testing

# This workflow will run `pytest` on the latest commit of the master
# branch, after having installed the package with pip.
# It will run on the latest Ubuntu and on the latest python.

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install the package from the git repo
      run: pip install ./

    - name: Install BLAST
      run: sudo apt-get install -y ncbi-blast+

    - name: Test with pytest
      run: crest4 --pytest