name: Test conda release on macOS

# This workflow will install the latest conda release of the package (not the
# master branch of the repository) and will run pytest on various platforms.
# This will run on the two latest python versions.

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.8', '3.9']
        os: [macos-latest]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          auto-activate-base: true

      - name: Install the package from anaconda
        run: conda install -y -c conda-forge -c xapple crest4

      - name: Install BLAST
        run: brew install blast

      - name: Run the pytest suite
        run: crest4 --pytest