name: Test PyPI release on macOS

# This workflow will install the latest PyPI release of the package (not the
# master branch of the repository) and will run pytest on various platforms.
# It will search both in the real PyPI index as well as the test PyPI.
# This will run on the two latest python versions.

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.8', '3.9']
        os: [macos-latest]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install the package from PyPI
        run: python -m pip install --extra-index-url https://test.pypi.org/simple/ crest4

      - name: Install BLAST
        run: brew install blast

      - name: Run the pytest suite
        run: crest4 --pytest