name: Test conda release

# This workflow will install the latest conda release of the package (not the
# master branch of the repository) and will run pytest on various platforms.
# This includes Ubuntu and macOS, as well as two different python versions.

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.8']
        os: [macos-latest]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Install the package from anaconda
        run: conda install -c conda-forge -c xapple crest4

      - name: Install BLAST
        run: sudo apt-get install -y ncbi-blast+

      - name: Run the pytest suite
        run: crest4 --pytest